limit_req_zone $binary_remote_addr zone=predict_limit:10m rate=10r/m;
server {
    listen 443 ssl;
    server_name identifruit.com;
    ssl_certificate /etc/letsencrypt/live/identifruit.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/identifruit.com/privkey.pem;
    location /static/ {
        alias /home/elexation/IdentiFruit/src/app/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
    location /predict {
        limit_req zone=predict_limit burst=5 nodelay;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10M;
    }
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
